/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnalogClock {
        "size": number;
        "timeZone": number;
    }
}
declare global {
    interface HTMLAnalogClockElement extends Components.AnalogClock, HTMLStencilElement {
    }
    var HTMLAnalogClockElement: {
        prototype: HTMLAnalogClockElement;
        new (): HTMLAnalogClockElement;
    };
    interface HTMLElementTagNameMap {
        "analog-clock": HTMLAnalogClockElement;
    }
}
declare namespace LocalJSX {
    interface AnalogClock {
        "size"?: number;
        "timeZone"?: number;
    }
    interface IntrinsicElements {
        "analog-clock": AnalogClock;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "analog-clock": LocalJSX.AnalogClock & JSXBase.HTMLAttributes<HTMLAnalogClockElement>;
        }
    }
}
